name: ss2
on: 
  push:
    branches:  
              - "main"
jobs:  
  ss2:
    name: ss2
    runs-on: ubuntu-latest
    steps:  
     - name : checkout
       uses: actions/checkout@v3

     - name: Build and push
       run: |
               docker build -t vaishnaviwohlig/ss2 .
               docker push 

