name: ss2
on: 
  push:
    branches:  
              - "main"
jobs:  
  ss2:
    name: ss2
    runs-on: ubuntu-latest
    steps:  
     - name : checkout
       uses: actions/checkout@v3

     - name: Build and push
       run: |
               docker login -u vaishnaviwohlig -p Dildosti@2512
               docker build -t vaishnaviwohlig/ss2:${{GITHUB.SHA}} .
               docker push vaishnaviwohlig/ss2:${{GITHUB.SHA}}

               yq e '.spec.template.spec.containers[0].image = "vaishnaviwohlig/ss2:${{ github.sha }}"' deployment.yaml -i
               git config user.name "Vaishnavi20011225"
               git config user.email "vaishnavi.korgaonkar@wohlig.com"
               git remote set-url origin https://Vaishnavi20011225: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@github.com/Vaishnavi20011225/ss2
               git add .
               git commit -m "image change"
               git status
               git push 

